[default_session]
startup_command = "tmux new-window -d && clear"
preview_command = "eza -l --git --icons --no-permissions --color=always --no-filesize --no-user --no-time {}"

[[session]]
name = "config"
path = "~/.config"
with_child = true

[[session]]
name = "go/github/dwiyanrp"
path = "~/c/go/src/github.com/dwiyanrp"
with_child = true

[[session]]
name = "js"
path = "~/c/js"
with_child = true

